
notify = [ "C:\\Users\\amu\\AppData\\Local\\OpenAI\\Codex\\runtimes\\cua_node\\f8d2abcb7481383b\\bin\\node_modules\\@oai\\sky\\bin\\windows\\codex-computer-use.exe", "turn-ended" ]
model = "fredrezones55/Qwen3.6-35B-A3B-Uncensored-HauhauCS-Aggressive"
model_reasoning_effort = "high"

model_provider = "ollama-launch-codex-app"

model_catalog_json = "C:\\Users\\amu\\.codex\\ollama-launch-models.json"

[marketplaces.openai-bundled]
last_updated = "2026-07-26T10:59:42Z"
source_type = "local"
source = '\\?\C:\Users\amu\.codex\.tmp\bundled-marketplaces\openai-bundled'

[marketplaces.openai-primary-runtime]
last_updated = "2026-07-24T16:47:48Z"
source_type = "local"
source = '\\?\C:\Users\amu\.cache\codex-runtimes\codex-primary-runtime\plugins\openai-primary-runtime'

[features]
fast_mode = true
js_repl = false
memories = true

[plugins."visualize@openai-bundled"]
enabled = true

[plugins."documents@openai-primary-runtime"]
enabled = true

[plugins."pdf@openai-primary-runtime"]
enabled = true

[plugins."spreadsheets@openai-primary-runtime"]
enabled = true

[plugins."presentations@openai-primary-runtime"]
enabled = true

[plugins."template-creator@openai-primary-runtime"]
enabled = true

[plugins."github@openai-api-curated"]
enabled = true

[plugins."chrome@openai-bundled"]
enabled = true

[plugins."computer-use@openai-bundled"]
enabled = true

[plugins."browser@openai-bundled"]
enabled = true

[mcp_servers.node_repl]
command = 'C:\Users\amu\AppData\Local\OpenAI\Codex\runtimes\cua_node\f8d2abcb7481383b\bin\node_repl.exe'
startup_timeout_sec = 120.0

[mcp_servers.node_repl.env]
BROWSER_USE_AVAILABLE_BACKENDS = "chrome,iab"
BROWSER_USE_CODEX_APP_BUILD_FLAVOR = "prod"
BROWSER_USE_CODEX_APP_VERSION = "26.721.41059"
CODEX_CLI_PATH = 'C:\Users\amu\AppData\Local\OpenAI\Codex\bin\69066b736e1e17a4\codex.exe'
CODEX_HOME = 'C:\Users\amu\.codex'
NODE_REPL_INSTRUCTIONS_USE_CASE_BROWSER = "Control the in-app browser in conjunction with the Browser Plugin."
NODE_REPL_INSTRUCTIONS_USE_CASE_CHROME = "Control the Chrome browser in conjunction with the Chrome Plugin. Prefer this method of controlling Chrome over alternatives (such as Computer Use) unless the user explicitly mentions an alternative."
NODE_REPL_NATIVE_PIPE_CONNECT_TIMEOUT_MS = "1000"
NODE_REPL_NODE_MODULE_DIRS = 'C:\Users\amu\AppData\Local\OpenAI\Codex\runtimes\cua_node\f8d2abcb7481383b\bin\node_modules'
NODE_REPL_NODE_PATH = 'C:\Users\amu\AppData\Local\OpenAI\Codex\runtimes\cua_node\f8d2abcb7481383b\bin\node.exe'
NODE_REPL_TRUSTED_BROWSER_CLIENT_SHA256S = "7ed52dae165c3bc22b6d24f282e2c1fbc87f6949fbbe037767a7418d8f517f01,e13fd947e846d3d306e9249dd3c73d14931b6494803dbafb16cef85e6add9506"
NODE_REPL_TRUSTED_CODE_PATHS = 'C:\Users\amu\.codex'
SKY_CUA_NATIVE_PIPE = "1"
SKY_CUA_NATIVE_PIPE_DIRECTORY = '\\.\pipe\codex-computer-use-bb8466cf-c966-45ce-be7a-a70c5904d786'

[mcp_servers.cloudflare]
url = "https://mcp.cloudflare.com/mcp"

[mcp_servers.cloudflare-docs]
url = "https://docs.mcp.cloudflare.com/mcp"

[mcp_servers.cloudflare-bindings]
url = "https://bindings.mcp.cloudflare.com/mcp"

[shell_environment_policy.set]
BROWSER_USE_AVAILABLE_BACKENDS = "chrome,iab"
NODE_REPL_TRUSTED_BROWSER_CLIENT_SHA256S = "7ed52dae165c3bc22b6d24f282e2c1fbc87f6949fbbe037767a7418d8f517f01,e13fd947e846d3d306e9249dd3c73d14931b6494803dbafb16cef85e6add9506"
NODE_REPL_TRUSTED_CODE_PATHS = 'C:\Users\amu\.codex'

[desktop]
conversationDetailMode = "STEPS_PROSE"
sansFontSize = 16
codeFontSize = 15
ambient-suggestions-enabled = true
followUpQueueMode = "steer"
show-context-window-usage = true
appearanceTheme = "dark"

[windows]
sandbox = "elevated"
[sandbox]
write_roots = [
    "E:\\OneDrive\\文档\\个人主页 2",
    "E:\\Obsidian\\codex 知识库"
]

[projects.'c:\users\amu\documents\codex']
trust_level = "trusted"

[projects.'e:\onedrive\文档\个人主页']
trust_level = "trusted"

[projects.'e:\onedrive\文档\个人主页 2']
trust_level = "trusted"

[model_providers.ollama-launch-codex-app]
name = "Ollama"
base_url = "http://127.0.0.1:11434/v1/"
wire_api = "responses"

[memories]
generate_memories = true
use_memories = true

